Replace tmpfs with ramfs  #19

diff --git a/debian/scripts/suspend/cryptsetup-suspend-wrapper b/debian/scripts/suspend/cryptsetup-suspend-wrapper
--- a/debian/scripts/suspend/cryptsetup-suspend-wrapper
+++ b/debian/scripts/suspend/cryptsetup-suspend-wrapper
@@ -27,11 +27,18 @@ mount_initramfs() {
         exit 1
     fi
 
-    # disable swap, so tmpfs is in RAM
-    swapoff -a
+    # Compare size of initramfs and available memory
+    # https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773
+    local MEM_AVAILABLE=`grep MemAvailable /proc/meminfo | awk '{print $2}'`
+    local MEM_SIZE=`expr "$MEM_AVAILABLE" \* 512`  # x * 1024 (byte)/ 2 (double space)
+    local INITRAMFS_SIZE=`gunzip -l "$INITRAMFS" | tail -n 1 | awk '{print $2}'`
 
-    # Limit tmpfs size to 200 MB, RAM is precious now
-    mount -t tmpfs -o mode=0755,size=200m tmpfs "$INITRAMFS_DIR"
+    if [ "$INITRAMFS_SIZE" -ge "$MEM_SIZE" ]; then
+        echo "Error: Not enough RAM" >&1
+        exit 1
+    fi
+
+    mount -t ramfs -o mode=0755 ramfs "$INITRAMFS_DIR"
 
     # extract initrd.img to initramfs dir
     if file -L "$INITRAMFS" | grep -q "ASCII cpio archive"; then
@@ -57,9 +64,6 @@ umount_initramfs() {
     # recursively unmount
     umount -R "$INITRAMFS_DIR"
     rmdir "$INITRAMFS_DIR"
-
-    # re-enable swap
-    swapon -a
 }
 
 CGROUP_FREEZER=
