d/t/cryptroot-*: Add UEFI support.
That enables testing on ARM architectures but also works on x86.  We
skip testing on debci's ARM boxes though because it just takes too long.

diff --git a/debian/tests/utils/cryptroot-common b/debian/tests/utils/cryptroot-common
--- a/debian/tests/utils/cryptroot-common
+++ b/debian/tests/utils/cryptroot-common
@@ -73,7 +73,7 @@ if [ "$DEB_DISTRIBUTION" = "UNRELEASED" ]; then
 fi
 
 # QEMU command and default options
-unset QEMU_MACHINE_TYPE QEMU_ACCEL QEMU_CPU_MODEL QEMU_SMP QEMU_MEMORY
+unset QEMU_MACHINE_TYPE QEMU_ACCEL QEMU_CPU_MODEL QEMU_SMP QEMU_MEMORY BOOT
 if [ -c /dev/kvm ] && dd if=/dev/kvm count=0 status=none; then
     QEMU_ACCEL="kvm"
 else
@@ -82,6 +82,7 @@ fi
 case "$DEB_BUILD_ARCHITECTURE" in
     # see `kvm -machine help` and `kvm -cpu help`
     amd64|i386)
+        BOOT="bios"
         if [ "$DEB_BUILD_ARCHITECTURE" = "amd64" ]; then
             QEMU_SYSTEM_CMD="qemu-system-x86_64"
         else
@@ -93,6 +94,18 @@ case "$DEB_BUILD_ARCHITECTURE" in
         else
             QEMU_CPU_MODEL="qemu$DEB_BUILD_ARCH_BITS,-svm,-vmx"
         fi
+    ;;
+    arm64)
+        BOOT="efi"
+        QEMU_SYSTEM_CMD="qemu-system-aarch64"
+        QEMU_MACHINE_TYPE="virt"
+        QEMU_CPU_MODEL="cortex-a72"
+    ;;
+    armhf)
+        BOOT="efi"
+        QEMU_SYSTEM_CMD="qemu-system-arm"
+        QEMU_MACHINE_TYPE="virt"
+        QEMU_CPU_MODEL="cortex-a15"
     ;;
     *) echo "ERROR: Unknown architecture $DEB_BUILD_ARCHITECTURE" >&2; exit 1;;
 esac
@@ -125,12 +138,18 @@ GUEST_POWERCYCLE=0
 case "$DEB_BUILD_ARCHITECTURE" in
     # see `ssh $porterbox.debian.org uname -r`
     amd64) KERNEL_ARCH="amd64";;
+    arm64) KERNEL_ARCH="arm64";;
+    armhf) KERNEL_ARCH="armmp-lpae";;
     i386) KERNEL_ARCH="686-pae";;
     *) echo "ERROR: Unknown architecture $DEB_BUILD_ARCHITECTURE" >&2; exit 1;;
 esac
 
 # at the very least we need a boot loader, a kernel, and an init system
-PKG_BOOTLOADER="grub-pc"
+case "$BOOT" in
+    bios) PKG_BOOTLOADER="grub-pc";;
+    efi) PKG_BOOTLOADER="grub-efi";;
+    *) echo "ERROR unknown boot method '$BOOT'" >&2; exit 1;;
+esac
 PKG_KERNEL="linux-image-$KERNEL_ARCH"
 PKG_INIT="systemd-sysv" # default pid1
 declare -a PKGS_EXTRA=() DRIVE_SIZES=( "2G" )
@@ -138,6 +157,34 @@ PKGS_EXTRA+=( "zstd" ) # default initrd compression, see #976054
 
 if [ -f "$TESTDIR/$TESTNAME.d/config" ]; then
     . "$TESTDIR/$TESTNAME.d/config" || exit 1
+fi
+
+unset EFI_CODE EFI_VARS
+if [ "$BOOT" = "efi" ]; then
+    case "$DEB_BUILD_ARCHITECTURE" in
+        amd64|i386)
+            efi_fw_pkg="ovmf"
+            EFI_CODE="/usr/share/OVMF/OVMF_CODE.fd"
+            EFI_VARS="/usr/share/OVMF/OVMF_VARS.fd"
+        ;;
+        arm64)
+            efi_fw_pkg="qemu-efi-aarch64"
+            EFI_CODE="/usr/share/AAVMF/AAVMF_CODE.fd"
+            EFI_VARS="/usr/share/AAVMF/AAVMF_VARS.fd"
+        ;;
+        armhf)
+            efi_fw_pkg="qemu-efi-arm"
+            EFI_CODE="/usr/share/AAVMF/AAVMF32_CODE.fd"
+            EFI_VARS="/usr/share/AAVMF/AAVMF32_VARS.fd"
+        ;;
+        *) echo "ERROR: Unknown architecture $DEB_BUILD_ARCHITECTURE for EFI boot" >&2; exit 1;;
+    esac
+    for p in "$EFI_CODE" "$EFI_VARS"; do
+        if [ ! -f "$p" ]; then
+            echo "Couldn't find $p, is the '$efi_fw_pkg' package installed?" >&2
+            exit 1
+        fi
+    done
 fi
 
 unset QEMU_PID
@@ -318,7 +365,12 @@ fi
 DEBIAN_IMG="$TEMPDIR/$DEB_DISTRIBUTION-$DEB_BUILD_ARCHITECTURE.img"
 create_debian_img "$DEBIAN_IMG"
 
-env PACKAGES="$PKG_BOOTLOADER linux-image-$KERNEL_VERSION $PKG_INIT ${PKGS_EXTRA[*]}" \
+case "$DEB_BUILD_ARCHITECTURE" in
+    arm64|armhf) CONSOLE="ttyAMA0";;
+    *) CONSOLE="ttyS0";;
+esac
+
+env PACKAGES="$PKG_BOOTLOADER linux-image-$KERNEL_VERSION $PKG_INIT ${PKGS_EXTRA[*]}" BOOT="$BOOT" CONSOLE="$CONSOLE" \
     "$TESTDIR/utils/mkinitramfs" "$TEMPDIR/linux-image" "$KERNEL_VERSION" "$TEMPDIR/initrd.img-$KERNEL_VERSION"
 rm -rf -- "$TEMPDIR/apt" "$TEMPDIR/linux-image" # don't need that anymore
 
@@ -344,6 +396,15 @@ for ((i=0; i < ${#DRIVE_SIZES[@]}; i++)); do
     )
 done
 
+if [ "$BOOT" = "efi" ]; then
+    # $EFI_VARS needs to be writable so guests can update their variables
+    install -Tm0644 -- "$EFI_VARS" "$TEMPDIR/efivars.fd"
+    QEMU_COMMON_ARGS+=(
+        -drive "file=$EFI_CODE,format=raw,if=pflash,unit=0,read-only=on"
+        -drive "file=$TEMPDIR/efivars.fd,format=raw,if=pflash,unit=1"
+    )
+fi
+
 QEMU_CHARDEV_LOG="logfile=$TEMPDIR/qemu.log,logappend=on"
 declare -a QEMU_STDIO_ARGS=(
     # setup is always fully unattended
@@ -356,7 +417,7 @@ QEMU_DEBIANIMG_DRIVE="file=$DEBIAN_IMG,format=raw,if=virtio,readonly=on,media=cd
 "$QEMU_SYSTEM_CMD" "${QEMU_COMMON_ARGS[@]}" "${QEMU_STDIO_ARGS[@]}" \
     -drive "$QEMU_DEBIANIMG_DRIVE" \
     -kernel "$TEMPDIR/vmlinuz-$KERNEL_VERSION" \
-    -append "console=ttyS0,115200n8" \
+    -append "console=$CONSOLE,115200n8" \
     -initrd "$TEMPDIR/initrd.img-$KERNEL_VERSION" \
     || exit 1
 
diff --git a/debian/tests/utils/init b/debian/tests/utils/init
--- a/debian/tests/utils/init
+++ b/debian/tests/utils/init
@@ -40,9 +40,30 @@ modprobe virtio_blk # /dev/vd[a-z]
 
 . /init.conf
 
+GUID_TYPE_MBR="024DEE41-33E7-11D3-9D69-0008C781F39F"       # MBR partition scheme
+GUID_TYPE_EFI="C12A7328-F81F-11D2-BA4B-00A0C93EC93B"       # EFI boot partition
 GUID_TYPE_BIOS_boot="21686148-6449-6E6F-744E-656564454649" # BIOS boot partition
 GUID_TYPE_Linux_FS="0FC63DAF-8483-4772-8E79-3D69D8477DE4"  # Linux filesystem data
 GUID_TYPE_LUKS="CA7D7CCB-63ED-4C53-861C-1742536059CC"      # LUKS partition
+
+if [ "$BOOT" = "bios" ]; then
+    BOOT_PARTITION_SIZE=2
+    BOOT_PARTITION_TYPE="$GUID_TYPE_BIOS_boot"
+elif [ "$BOOT" = "efi" ]; then
+    BOOT_PARTITION_SIZE=63
+    BOOT_PARTITION_TYPE="$GUID_TYPE_EFI"
+else
+    echo "ERROR unknown boot method '$BOOT'" >&2
+    exit 1
+fi
+
+# format the target disk and create a BIOS/EFI partition
+sfdisk /dev/vda <<-EOF
+	label: gpt
+	unit: sectors
+
+	start=$((1024*2)), size=$((BOOT_PARTITION_SIZE*1024*2)), type=$BOOT_PARTITION_TYPE
+EOF
 
 . /init.setup
 
@@ -56,6 +77,20 @@ done
 # setup hosts(5) and hostname(5)
 echo "$HOSTNAME" >/target/etc/hostname
 echo "127.0.0.1 localhost $HOSTNAME" >/target/etc/hosts
+
+# EFI
+if [ "$BOOT" = "efi" ]; then
+    modprobe efivarfs
+    mount -t efivarfs efivarfs /sys/firmware/efi/efivars
+
+    mkfs.vfat -F 32 /dev/vda1
+    mkdir /target/boot/efi
+    mount -t vfat /dev/vda1 /target/boot/efi
+
+    cat >>/target/etc/fstab <<-EOF
+		UUID=$(blkid -s UUID -o value /dev/vda1) /boot/efi auto defaults 0 2
+	EOF
+fi
 
 # move pseudo and temporary filesystems to /target
 mount -no move /dev /target/dev
@@ -108,7 +143,7 @@ cat >/target/etc/default/grub <<-EOF
 	GRUB_DEFAULT=0
 	GRUB_TIMEOUT=0
 	GRUB_CMDLINE_LINUX_DEFAULT=""
-	GRUB_CMDLINE_LINUX="console=tty0 console=hvc0 console=ttyS0,115200n8"
+	GRUB_CMDLINE_LINUX="console=tty0 console=hvc0 console=$CONSOLE,115200n8"
 	GRUB_DISABLE_RECOVERY=true
 	GRUB_TERMINAL="console serial"
 	GRUB_SERIAL_COMMAND="serial --speed=115200"
@@ -146,6 +181,9 @@ mount -no move /target/proc /proc
 mount -no move /target/run /run
 mount -no move /target/sys /sys
 
+if [ "$BOOT" = "efi" ]; then
+    umount /target/boot/efi
+fi
 umount /target/media
 sh -eux /init.bottom
 
diff --git a/debian/tests/utils/mkinitramfs b/debian/tests/utils/mkinitramfs
--- a/debian/tests/utils/mkinitramfs
+++ b/debian/tests/utils/mkinitramfs
@@ -44,7 +44,10 @@ cat >"$DESTDIR/init.conf" <<- EOF
 	HOSTNAME="$TESTNAME"
 	export HOSTNAME
 	PACKAGES="$PACKAGES"
+	BOOT="$BOOT"
+	CONSOLE="$CONSOLE"
 EOF
+
 for p in setup preinst postinst bottom; do
     # setup: sourced after creating the BIOS or EFI boot partition
     # preinst: run in chroot after debootstrap, but before installing extra packages
@@ -55,11 +58,16 @@ for p in setup preinst postinst bottom; do
     fi
 done
 
+MODULES="dm_crypt ext4"
+if [ "$BOOT" = "efi" ]; then
+    MODULES="$MODULES efivarfs nls_ascii nls_cp437 vfat"
+fi
+
 depmod -ab "$EXTRACT_DIR" "$KERNEL_VERSION"
-for kmod in virtio_blk virtio_pci virtio_rng dm_crypt \
+for kmod in virtio_blk virtio_pci virtio_rng \
         "$EXTRACT_DIR/lib/modules/$KERNEL_VERSION"/kernel/arch/*/crypto/*.ko \
         "$EXTRACT_DIR/lib/modules/$KERNEL_VERSION"/kernel/crypto/*.ko \
-        ext4; do
+        $MODULES; do
     kmod="${kmod##*/}"
     modprobe -aid "$EXTRACT_DIR" -S "$KERNEL_VERSION" --show-depends "${kmod%.ko}"
 done | while read -r insmod kmod; do
@@ -104,6 +112,14 @@ for x in cryptsetup lvm mke2fs; do
         copy_exec "/sbin/$x"
     fi
 done
+
+if [ "$BOOT" = "efi" ]; then
+    if [ ! -x "/sbin/mkfs.vfat" ]; then
+        echo "Couldn't find mkfs.vfat, is the 'dosfstools' package installed?" >&2
+        exit 1
+    fi
+    copy_exec /sbin/mkfs.vfat
+fi
 
 cp -pLt "$DESTDIR/lib" /lib/klibc-*.so
 for cmd in cat chroot ln ls mkdir mount mv sh umount uname; do
